sudo: false
cache:
  directories:
    - "$HOME/.stack/"
matrix:
  include:
    - env: RESOLVER=lts-2
    - env: RESOLVER=lts-3
    - env: RESOLVER=nightly
  allow_failures:
    - env: RESOLVER=nightly
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - ./latest $RESOLVER > stack-travis.yaml
  - export STACK_YAML=stack-travis.yaml
  - stack update
install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot
  # install jinja2
  - pip install --user Jinja2
  # install hpc-coveralls
  - stack --no-terminal --skip-ghc-check install hpc-coveralls

script:
  - stack --no-terminal --skip-ghc-check test --coverage
  - stack --no-terminal --skip-ghc-check sdist

  # check that the generated source-distribution can be built & installed
  #- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
  #  (cd dist/;
  #  if [ -f "$SRC_TGZ" ]; then
  #    cabal install --force-reinstalls "$SRC_TGZ";
  #  else
  #    echo "expected '$SRC_TGZ' not found";
  #    exit 1;
  #  fi)

after_script:
  - hpc-coveralls --exclude-dir=test tests

# EOF
